version: '3.1'

services:

  store:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "random"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
